# Generated by Django 3.2.16 on 2023-12-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231207_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InStrSpending', models.FloatField()),
                ('Discount', models.FloatField()),
                ('TVSpending', models.FloatField()),
                ('StockRate', models.FloatField()),
                ('Price', models.FloatField()),
                ('Radio', models.FloatField()),
                ('OnlineAdsSpending', models.FloatField()),
                ('Profit', models.FloatField()),
            ],
        ),
    ]
