# Generated by Django 3.2.16 on 2023-12-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20231212_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='predicted_price',
            new_name='predicted_sale',
        ),
    ]
